# status bar
#set-option -g status-utf8 on
#set -g utf8 on

set-option -g default-shell /bin/bash

set -g status-interval 1
set -g status-position bottom
set -g status-justify left # center align window list
set -g status-left-length 30
set -g status-right-length 100
set -g status-left ' '
#set -g status-left '#[fg=yellow][#[fg=green]#H #[fg=black]• #[fg=green,bright]#(whoami)#[default]#[fg=yellow]]: '
#set -g status-right '#[fg=green]#(tmux-mem-cpu-load 1) #[]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") %a%l:%M:%S %p %Y-%m-%d'
set -g status-right '#{?GITMUX_REPO,#[fg=white]#[bg=brightblack] #[fg=red]❓#{GITMUX_UNTRACKED} #[fg=yellow]▲ #{GITMUX_CHANGED} #[fg=green]● #{GITMUX_STAGED} #[fg=white] #[fg=green]↑#{GITMUX_COMMITS_AHEAD} #[fg=red]↓#{GITMUX_COMMITS_BEHIND} #[fg=white] #{?GITMUX_REMOTE,#{GITMUX_BRANCH},#[fg=white]#{GITMUX_BRANCH} #[fg=white] #{GITMUX_REPO_NAME}},}'

# default statusbar colors
set -g status-fg white
set -g status-bg default
set -g status-attr bright

# default window title colors
set-window-option -g window-status-fg white
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg black
set-window-option -g window-status-current-bg green
set-window-option -g window-status-current-attr bright

# C-b is not acceptable -- Vim uses it
unbind C-b
set-option -g prefix C-a
bind-key C-a last-window

bind -n S-Right next-window
bind -n S-Left previous-window

bind-key -n M-Left swap-window -t -1
bind-key -n M-Right swap-window -t +1

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Highlight active window
#set-window-option -g window-status-current-bg green
#set-window-option -g window-status-current-style fg=white,bg=green,bright

# Vi copypaste mode
set-window-option -g mode-keys vi
#bind-key -t vi-copy 'v' begin-selection
#bind-key -t vi-copy 'y' copy-selection

# hjkl pane traversal
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# auto window rename
#set-window-option -g automatic-rename
set-window-option -g automatic-rename off
set-option -g allow-rename off
# rm mouse mode fail
# set -g mode-mouse off

# color
set -g default-terminal "screen-256color"

# Sane scrolling
# TODO: make sure this works in OSX
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

set-option -g history-limit 10000

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '0phoff/gitmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'

# Actual full version of the statusline I use
